version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  public:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - html/firulais.net.ar:/usr/share/nginx/html:ro
      - images:/usr/share/nginx/html/assets/images:ro
    environment:
      - VIRTUAL_HOST=firulais.net.ar,www.firulais.net.ar
      - LETSENCRYPT_HOST=firulais.net.ar,www.firulais.net.ar
      - LETSENCRYPT_EMAIL=fofware@gmail.com
    depends_on:
      - nginx-proxy
      - letsencrypt

  admin:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - html/firulais.net.ar:/usr/share/nginx/html:ro
      - images:/usr/share/nginx/html/assets/images:ro
    environment:
      - VIRTUAL_HOST=admin.firulais.net.ar
    depends_on:
      - nginx-proxy

  images:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - images:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=images.firulais.net.ar
    depends_on:
      - nginx-proxy
